### ISSUE TITLE
writematrix function error in inversion

### ISSUE THREAD

**Issue by Abhishek7-1** [LucaDeSiena/MuRAT#25]
Sir every time i run the code as instructed it throws the error.  I am not able to resolve why it is giving this error on that particular line but somehow i think  writematrix is not working for me in MATLAB2017a. pls help me as soon as possible.
![Screenshot (14)](https://user-images.githubusercontent.com/83660470/162973040-4898caa9-556d-404a-97be-822903df316e.png)

**Comment by LucaDeSiena** [comment]
As you probably guessed, you need a later version of Matlab to run the code.
