### ISSUE TITLE
index no.related issue

### ISSUE THREAD

**Issue by Abhishek7-1** [LucaDeSiena/MuRAT#26]
Sir, I have started Murat 3 as my Dissertation work. Sir, I worked on example data of Romania and it gave me the desired output. But again when I tried to use some other data as an input file, it gave the error as shown in the screenshot attached to this mail. I am sharing the necessary data and files. Please have a look over it and suggest to me where I am going wrong. I hope to hear from you soon.
data link:
https://drive.google.com/drive/folders/1UXgseTKPuFEN3AmDRIjvgAyv_YfVoXYV?usp=sharing
![Screenshot (17)](https://user-images.githubusercontent.com/83660470/169608885-c395ec95-7f8e-419a-b83f-03d6ea2721bc.png)

**Comment by LucaDeSiena** [comment]
The new version does not have this problem. Also, try the sequential module.
